
var PuzzleConstants = {
  PUZZLES_RECEIVED: "PUZZLES_RECEIVED",
  GAME_RECEIVED: "GAME_RECEIVED",
  LETTER_ENTERED: "LETTER_ENTERED",
  USER_DATA_RECEIVED: "USER_DATA_RECEIVED",
  SWITCH_DIRECTION: "SWITCH_DIRECTION",
  ACROSS_CLUE: "ACROSS_CLUE",
  DOWN_CLUE: "DOWN_CLUE",
  PREVIOUS_GAME: "PREVIOUS_GAME",
  PUZZLE_RECEIVED: "PUZZLE_RECEIVED",
  ARROW_MOVE: "ARROW_MOVE",
  CLEAR: "CLEAR"
}

module.exports = PuzzleConstants;
